'''Write a program to input eight numbers from the user and display all the unique
numbers (once).'''
s = set()
numbers = input("Enter num 1: ")
s.add(int(numbers))
numbers = input("Enter num 2: ")
s.add(int(numbers))
numbers = input("Enter num 3: ")
s.add(int(numbers))
numbers = input("Enter num 4: ")
s.add(int(numbers))
numbers = input("Enter num 5: ")
s.add(int(numbers))
numbers = input("Enter num 6: ")
s.add(int(numbers))
numbers = input("Enter num 7: ")
s.add(int(numbers))
numbers = input("Enter num 8: ")
s.add(int(numbers))
print(s)